adjust nightly test

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -1,27 +1,49 @@
-name: Daily compatibility check against latest polkadot
+name: Nightly test
 
 on:
+  # schedule:
+  #   - cron: '0 0 * * *'
   workflow_dispatch:
-    inputs:
-      gitlab_pipeline:
-        description: 'Link to failed pipeline'
-        required: true
-      gitlab_test_job_status:
-        description: 'GitLab test job status'
-        required: true
 
 jobs:
-  announce-status:
+  nightly-test:
     runs-on: ubuntu-latest
+    container: paritytech/ci-unified:bullseye-1.74.0
+
     steps:
-      - name: Announce a status
-        run: echo  ${{ inputs.gitlab_test_job_status }}
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Cache Rust dependencies
+        uses: swatinem/rust-cache@v2
+        with:
+          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
+
+      - name: Run nightly tests
+        run: |
+          git clone -b master --depth 1 https://github.com/paritytech/polkadot-sdk.git polkadot-sdk
+          cd polkadot-sdk
+          cargo build -p polkadot --release --features fast-runtime
+          mkdir -p ~/.local/bin
+          mv ./target/release/polkadot /usr/bin
+          mv ./target/release/polkadot-execute-worker /usr/bin
+          mv ./target/release/polkadot-prepare-worker /usr/bin
+          polkadot --version
+          cd -
+          rm -rf polkadot
+          cd staking-miner-playground
+          cargo build --release --features test-trimming
+          mv ./target/release/staking-miner-playground /usr/bin
+          staking-miner-playground --version
+          cd -
+          RUST_LOG=info cargo test --workspace --all-features -- --nocapture
+          cargo clean
 
   create-an-issue:
-    if: ${{ inputs.gitlab_test_job_status == 'failed' }}
+    if: failure()
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout staking-miner sources
+      - name: Checkout repository
         uses: actions/checkout@v4
 
       - name: Create an issue
@@ -39,5 +61,5 @@ jobs:
           # create a new one if we only find closed versions):
           search_existing: open
 
-      - name: Fail workflow if tests failed
-        run: exit 1
+      # - name: Fail workflow if tests failed
+      #   run: exit 1
